name: hidebiyori
description: Application for hidebiyori

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://firebase.google.com/docs/flutter/setup
  # https://firebase.flutter.dev/docs/overview/
  # https://pub.dev/publishers/firebase.google.com/packages
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0

  # remove the leading hash (#) from the URL
  url_strategy: ^0.2.0

  # launching a URL
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # https://firebase.flutter.dev/docs/testing/testing/
  fake_cloud_firestore: ^1.1.2

# https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # https://flutter.dev/assets-and-images/#resolution-aware.
  # https://flutter.dev/assets-and-images/#from-packages
  # https://flutter.dev/custom-fonts/#from-packages
